services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart : always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: home-energy-tracker
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
      - db-data:/var/lib/mysql

volumes:
  db-data:


