spring.application.name=ingestion-service

server.port=8083
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.template.default-topic=energy-usage
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

simulation.endpoint=http://localhost:8083/api/v1/ingestion

simulation.request-per-interval=10000

simulation.interval-ms=5000
simulation.parallel-threads=10

